// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DecodeName() {
  return window['go']['main']['App']['DecodeName']();
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['main']['App']['DisconnectAll']();
}

export function ExitFullscreen() {
  return window['go']['main']['App']['ExitFullscreen']();
}

export function Fullscreen() {
  return window['go']['main']['App']['Fullscreen']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetMemberships() {
  return window['go']['main']['App']['GetMemberships']();
}

export function ListenConn(arg1, arg2) {
  return window['go']['main']['App']['ListenConn'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
