// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {websocket} from '../models';

export function Connect(arg1:string):Promise<string>;

export function Disconnect(arg1:string):Promise<string>;

export function GetHistory(arg1:string):Promise<Array<main.Message>>;

export function GetMemberships():Promise<Array<string>>;

export function ListenConn(arg1:websocket.Conn):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Logout():Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<boolean>;
